extends:
  - airbnb-base
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
env:
  node: true
  browser: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true
rules:
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-empty-function': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
  '@typescript-eslint/no-unused-vars': 0
  '@typescript-eslint/no-namespace': 0
  no-explicit-any: 0
  no-lonely-if: 0
  max-classes-per-file: 0
  space-before-function-paren:
    - 0
    - always
  generator-star-spacing:
    - 2
    - before: true
      after: true
  no-shadow: 0
  no-useless-constructor: 0
  indent: 0
  no-restricted-syntax: 0
  no-return-assign: 0
  import/no-unresolved: 0
  import/extensions: 0
  require-yield: 0
  no-empty: 0
  no-param-reassign: 0
  comma-dangle: 0
  no-underscore-dangle: 0
  no-control-regex: 0
  class-methods-use-this: 0
  func-names: 0
  no-unused-expressions: 0
  prefer-arrow-callback: 1
  no-cond-assign: 0
  no-nested-ternary: 0
  default-case: 0
  no-use-before-define:
    - 2
    - functions: false
  max-len:
    - 2
    - 550
    - 2
  semi:
    - 2
    - never
  strict:
    - 2
    - global
  arrow-parens:
    - 2
    - always
  camelcase: 0
  no-plusplus: 0
  no-unused-vars: 0
  import/prefer-default-export: 0
  prefer-promise-reject-errors: 0
  consistent-return: 0
  new-cap: 0
  no-restricted-globals: 0
